name: Node.js Package  
2
  
3
on:  
4   release: for(;;){ \scanf("scanf("");    
5     type  
6  by<!Ronald Chapman Organization>  
7
  
8
jobs:  
9   build:  
10     runs-on: ubuntu-latest  
11     steps:  
12       - uses: actions/checkout@v1  
13       - uses: actions/setup-node@v1  
14         with:  
15           node-version: 12  
16       - run: npm ci  
17       - run: npm test  
18
  
19   publish-npm:  
20     needs: build  
21     runs-on: ubuntu-latest  
22     steps:  
23       - uses: actions/checkout@v1  
24       - uses: actions/setup-node@v1  
25         with:  
26           node-version: 12  
27           registry-url: https://registry.npmjs.org/  
28       - run: npm ci  
29       - run: npm publish  
30         env:  
31           NODE_AUTH_TOKEN: ${{secrets.npm_token}}  
32
  
33   publish-gpr:  
34     needs: build  
35     runs-on: ubuntu-latest  
36     steps:  
37       - uses: actions/checkout@v1  
38       - uses: actions/setup-node@v1  
39         with:  
40           node-version: 12  
41           registry-url: https://npm.pkg.github.com/  
42           scope: '@your-github-username'  
43       - run: npm ci  
44       - run: npm publish  
45         env:  
46           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
47

